### ISSUE TITLE
Addon still has Bower dependency

### ISSUE THREAD

**Issue by Subaku** [Panman8201/ember-bootstrap-switch#19]
Hello,

I came across this lovely addon and after installing it into my project I noticed there's still a dependency on Bower. I was wondering if there's any plans to drop this dependency?

Thanks!

**Comment by Panman82** [comment]
It certainly could be migrated away from bower. However, the library that this addon relies on, [bootstrap-switch](https://github.com/Bttstrp/bootstrap-switch), [hasn't had recent activity](https://github.com/Bttstrp/bootstrap-switch/commits/master) so [I've somewhat depreciated this addon](https://github.com/Panman8201/ember-bootstrap-switch/commit/02028022ecddb3ee4b6c7bb81859a8578e692e18). There was a short time where someone else took over the project but it looks like they've also dropped development. So, what I'm getting at is that I'm not sure that you'll want to use this addon now days. Certainly unfortunate because it is a nice solution for bootstrap.

**Comment by Subaku** [comment]
I did in fact notice the deprecation notice for this addon. Figured I'd ask anyway :)

Thanks!
